# Generated by Django 4.2.7 on 2023-11-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_types',
            new_name='product_type',
        ),
    ]
