# Generated by Django 4.2.7 on 2023-11-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='attributes',
            field=models.ManyToManyField(related_name='product_type_attributes', through='product.ProductTypeAttribute', to='product.attribute'),
        ),
    ]
