# Generated by Django 4.2.7 on 2023-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='attribute_values',
            field=models.ManyToManyField(related_name='product_line_attribute_value', through='product.ProductLineAttributeValue', to='product.attributevalue'),
        ),
    ]
