# Generated by Django 4.2.7 on 2023-11-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
