# Generated by Django 4.2.7 on 2023-11-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productline_attribute_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='product_attribute',
            new_name='attribute',
        ),
    ]
