# Generated by Django 4.2.7 on 2023-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.SmallIntegerField(choices=[(10, 'Paid'), (-10, 'Not paid')], default=-10),
        ),
    ]
